name: angular-perf
version: 0.10.0
description: Angular benchmarks
dependencies:
  angular:
    path: ..
dev_dependencies:
  benchmark_harness: '>=1.0.4 <2.0.0'
  unittest: '>=0.11.0 <0.12.0'
  mock: '>=0.11.0 <0.12.0'
  web_components: '>=0.3.4 <0.4.0'
