name: angularperf
version: 0.10.0
description: Angular benchmarks
dependencies:
  angular:
    path: ..
  browser: '>=0.10.0 <0.11.0'
  web_components: '>=0.5.0 <0.7.0'
  benchmark_harness: '>=1.0.0'
  unittest: '>=0.10.1 <0.12.0'
  mock: '>=0.10.0 <0.12.0'
transformers:
- angular
- $dart2js:
    minify: false
    checked: false
    commandLineOptions: [--dump-info]
