name: angular_dart_example
version: 0.0.1
dependencies:
  angular:
    path: ../
  quiver: '>=0.18.2 <0.19.0'
  browser: '>=0.10.0 <0.11.0'
  web_components: '>=0.5.0 <0.7.0'

transformers:
- angular:
    html_files:
      - web/bouncing_controller.html
      - web/form_controller.html
