name: angular_dart_example
version: 0.0.1
dependencies:
  angular:
    path: ../
  browser: any
  quiver: '>=0.18.0<0.19.0'
  unittest: any
  web_components: any

transformers:
- angular:
    html_files:
      - web/bouncing_balls_tpl.html
      - web/form_controller.html
