language: node_js
node_js:
- "0.11"
env:
  matrix:
  - JOB=unit-stable
    CHANNEL=stable
    TESTS=dart2js
    BROWSERS=SL_Firefox,SL_Chrome
  - JOB=unit-dev
    CHANNEL=dev
    TESTS=dart2js
    BROWSERS=SL_Firefox,SL_Chrome
  - JOB=unit-dev
    CHANNEL=dev
    TESTS=vm
    BROWSERS=DartiumWithWebPlatform
  - JOB=unit-stable
    CHANNEL=stable
    TESTS=vm
    BROWSERS=DartiumWithWebPlatform
  global:
  - secure: "UiibgQ+Phh+k/tXudlYC3uz7Qt6xyAD1voY4s1wJqebGjvq7W/B+fp5jlnnF0GAQqryJTTJh6n+aBpCw+DyYCxD6Fss5/1/nW+sjlqL3mTGc0I38OeEjYPurbDu+Ql28v6PadMaU99NQ88gGHiEvb0YsutdTlgJPcBk52s3vCjk="
  - secure: "C9rsosMHZx7N/F1AYgB/66lqH0QNrA+uAPMbOeTmUubBBmn2N6/6GKAiCkMSFz45iX6Xb9z+0E9+jrdUPjVN/3asPd8WTTg/1weQENUuBtxAfCpeGU0qLWdYif3YfquCs9ZHW6J9QUJpF0+frqpJnjwLP2MmJbChEeMa/yo4JDk="
  - FIREFOX_VERSION="29.0"
  - CHROME_BIN=/usr/bin/google-chrome
  - secure: "AKoqpZ699egF0i4uT/FQ5b4jIc0h+KVbhtVCql0uFxwFIl2HjOYgDayrUCAf6USfpW0LghZxJJhBamWOl/505eNSe9HvEd8JLg/to+1Fo9xi9llsu5ehmNH31/5pue4EvsrVuEap1qqL6/BNwI2cAryayU0p5tV0g8gL5h4IxG8="

# Don't test these branches.
branches:
  except:
    - g3v1x

before_install:
- export DISPLAY=:99.0
- ./scripts/travis/install.sh
before_script:
- ./scripts/travis/setup.sh
script:
- ./scripts/travis/build.sh
after_success:
- ./scripts/travis/after-success.sh
