language: node_js
node_js:
- 0.1
env:
  matrix:
  - JOB=unit-stable
    TESTS=vm
  - JOB=unit-dev
    TESTS=vm
  - JOB=unit-stable
    TESTS=dart2js
  - JOB=unit-dev
    TESTS=dart2js
  global:
  - CHROME_BIN=/usr/bin/google-chrome
  - secure: "ZSUCLuDjvKEFmgjAd3GpUNCNkdjE66dEIiBfW+EfN0dv2+QHx/MHL4hRyKk2qbGjCr/suR9JWgmNE+Yu1A4fwzcYN52ehgyoLUCTL9YDk+XkFdFWpnjJ8364TDcDuJA0oxwcqJ9E3XUPv6sq1mbcX6DlkPKco7ZT8TLtGmd0nGA="
before_install:
- export DISPLAY=:99.0
- ./scripts/travis/install.sh
before_script:
- ./scripts/travis/setup.sh
script:
- ./scripts/travis/build.sh
after_script:
- ./scripts/travis/presubmit.sh
- ./scripts/travis/publish-docs.sh

